### PR TITLE
Using express

### PR DESCRIPTION
**Pull request by UserUNP**
Redone the entire server using Express for more code legibility and abstraction
everything works the same way i added comments to explain what some things do

### CODE REVIEW

**Comment by UserUNP** [comment]
Using express & a rate limiter

**Comment by UserUNP** [comment]
i wanted to make the second commit a separate pull request but anyways lol

**Review by AstroSquared — APPROVED** [review]
looks cool (idk if this approve counts im not contributor)

**Comment by GeorgeRNG** [comment]
Each endpoint must start with `/api/`, or a * wildcard it to allow the fact that every endpoint must be on api or perhaps a test alternative name.

This runs on the main file, which can never be seen on the host since when you get something like `https://dfonline.dev/api/db` the app will see you requesting something at the URL `api/db`, not `db`.

I'll just fix it myself.

**Pull request merged**
